% vi: ft=tex
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{presentation}[2021/11/08 kshi thesis presentation class]

\LoadClass{beamer}

\RequirePackage{mathtools}
\RequirePackage{microtype}
\RequirePackage{libertinus}

\RequirePackage{cancel}
\RequirePackage{array}
\RequirePackage{booktabs}

\RequirePackage{parskip}
\RequirePackage{enumitem}
\RequirePackage{tikz}
\usetikzlibrary{calc}
\usetikzlibrary{positioning}
\usetikzlibrary{arrows.meta}
\usetikzlibrary{decorations}

\RequirePackage{amsthm}
\RequirePackage{thmtools}
\RequirePackage{tcolorbox}
