setup:
  @mkdir -p '_build/_tikz'
  @ln -sf '_build/_tikz'

build: setup
  latexmk -interaction='nonstopmode' -xelatex 'midyear-report.tex'

dev: setup
  latexmk -pvc -interaction='nonstopmode' -xelatex 'midyear-report.tex'

view:
  nohup zathura '_build/midyear-report.pdf' > '/dev/null' 2> '/dev/null' &

