name: "build"
on:
  push:
    branches:
      - "main"
jobs:
  build-midyear-report:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "./.action"
        with:
          name: "midyear-report"
      - uses: "actions/upload-artifact@v2"
        with:
          name: "midyear-report"
          path: "midyear-report/_build/midyear-report.pdf"
  release:
    runs-on: "ubuntu-latest"
    needs: ["build-midyear-report"]
    steps:
      - uses: "actions/download-artifact@v2"
        with:
          name: "midyear-report"
          path: "/tmp/out/midyear-report.pdf"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "PDFs"
          automatic_release_tag: "latest"
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          files: |
            /tmp/out/midyear-report.pdf
